### ISSUE TITLE
InstanceID.getToken cause new token "from" property for every upstream message at the XMPP server

### ISSUE THREAD

**Issue by henrik-lindqvist** [google/gcm#90] opened 2015-08-21 18:57 UTC
http://stackoverflow.com/questions/30741078/identifying-sender-of-upstream-gcm-message

Calling GoogleCloudMessaging.getInstance(context).register(senderId) instead of getToken(senderId, "GCM") seems to resolve the issue, the XMPP server will then receive the correct token, every time, in the "from" property of the upstream message.

My device is running CyanogenMod, so the Google Play services app doesn't update automatically. Since the old register() work, this issue is likely caused by a bug in the google-play-services_lib when talking to an older version of the GMS app.

**Comment by silvolu** [comment] 2015-09-02 22:35
Duplicate of #94, please follow the other issue.

**Closed as completed by silvolu** 2015-09-02 22:35 UTC

**Comment by henrik-lindqvist** [comment] 2015-09-02 23:33
@silvolu I've reported an GCM Developer Support Inquiry issue [6-9096000008404]

**Comment by silvolu** [comment] 2015-09-02 23:36
Perfect, thanks!
