### ISSUE TITLE
enable_bitcode issue 

### ISSUE THREAD

**Issue by hadycodes** [google/gcm#99] opened 2015-09-17 14:28 UTC
I have that error after I updated Xcode 
ld: '.../Libraries/libGGLCloudMessaging.a(GGLContext+CloudMessaging.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

what can I do, or do I need to wait for the new release :/ 
because we supposed to launch this app this week and it will be huge problem for me if I didn't.

**Comment by silvolu** [comment] 2015-09-21 17:42
duplicate of #91
@HadiIOS we will enable bitcode in our next release, but right now I cannot tell you exactly when it will be published. If you're not building for watchOS, bitcode is just a recommendation, so you can disable it. If you're building for watchOS though it's required, so you'll have to wait for the next release.

**Closed as completed by silvolu** 2015-09-21 17:42 UTC
