### ISSUE TITLE
Release to the Maven central repo

### ISSUE THREAD

**Issue by highsource** [google/gcm#150] opened 2016-01-09 00:46 UTC
When/if #149 is merged, could you please release to the central Maven repo? Many thanks.

**Comment by kroikie** [comment] 2016-01-09 01:48
I am currently working on this. This will be made available very soon.

**Comment by maksimu** [comment] 2016-01-09 04:58
Possible duplicate of #23

**Comment by highsource** [comment] 2016-01-09 07:22
Great, thank you.

**Comment by highsource** [comment] 2016-01-14 11:34
@kroikie Do you need any help with this? I'm blocked by this in a couple of issues, but don't want to deploy my fork the the central.

**Comment by kroikie** [comment] 2016-01-19 21:31
The library is now available:

Group: com.google.gcm
Artifact: gcm-server
Version: 1.0.0

Thank you for your patience.

**Closed as completed by kroikie** 2016-01-19 21:31 UTC

**Comment by highsource** [comment] 2016-01-20 08:03
Great, many thanks.
