### ISSUE TITLE
Files in app Document folder

### ISSUE THREAD

**Issue by dral3x** [google/gcm#120] opened 2015-10-16 15:30 UTC
The GCM library put internal files inside the app `Documents` directory but it should not do that. 
This make impossible to me turn `UIFileSharingEnabled` on because user can interact with these files.

Files are
- `com.google.iid-keypair.plist`
- `com.google.iid-tokens.plist`
- `g-checkin.plist`

As reference, my question on [SO](http://stackoverflow.com/questions/32989292/google-clould-messaging-ios-put-files-in-default-app-documents-folder)

**Comment by mohitsharma0690** [comment] 2015-11-12 02:50
@dral3x This will be fixed in the next library update which should come out soon.

**Comment by dral3x** [comment] 2015-11-12 08:06
Great news! Thanks guys

**Closed as completed** 2015-11-12 10:50 UTC

**Comment by vladogrigorov** [comment] 2016-05-05 14:47
Exactly the same issue happens to me. I download these GCM pods:

```
Using GGLInstanceID (1.2.1)
Using Google (2.0.4)
Using GoogleCloudMessaging (1.2.0)
Using GoogleIPhoneUtilities (1.2.0)
Using GoogleInterchangeUtilities (1.2.0)
Using GoogleNetworkingUtilities (1.2.0)
Using GoogleSymbolUtilities (1.1.0)
Using GoogleUtilities (1.3.0)

```

Then I copy library and header files to my project, which does not use CocoaPods. GCM works fine, however it always creates these files in the Documents directory:
- com.google.iid-keypair.plist
- com.google.iid-tokens.plist
- g-checkin.plist
- rmq2.sqlite

I see the issue is closed, but I can't find GCM version where this has been fixed.

**Comment by mkll** [comment] 2016-09-07 23:09
The latest available version of GCM for iOS still creates at least `rmq2.sqlite` in the Documents directory. Shame on you, Google! :(

**Comment by jielu** [comment] 2016-09-12 21:45
rmq2.sqlite has been moved from Documents directory to ApplicationSupport directory since FirebaseMessaging v1.1.1. FirebaseInstanceID also stops writing to Documents directory since v1.0.8. Both versions were released in July.

P.S. unfortunately this is not the best place to receive support for this type of issues now.
Please choose one of the available channels from https://firebase.google.com/support/

**Comment by jielu** [comment] 2016-09-12 21:56
Also note, we don't have an ETA to fix this issue to GoogleCloudMessaging library. GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future.
